### ISSUE TITLE
embed font in slick theme css

### ISSUE THREAD

**Issue by kyuwoo-choi** [gs-shop/vue-slick-carousel#52]
![image](https://user-images.githubusercontent.com/1215767/70957314-131e1a80-20b9-11ea-917d-19a8451a2708.png)

```css
.slick-loading .slick-list
{
    background: #fff url('./ajax-loader.gif') center center no-repeat;
}

/* Icons */
@font-face
{
    font-family: 'slick';
    font-weight: normal;
    font-style: normal;

    src: url('./fonts/slick.eot');
    src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
}
```

ref: #37
