### ISSUE TITLE
slide no show on page

### ISSUE THREAD

**Issue by blackinitial** [gs-shop/vue-slick-carousel#77]
i use nuxt on web profile, in development is work, slick slider is showing, but in production SSR not showing.
i was debugging on console, and i get a bug on css slick slider.

in development i get:
```css
.slick-initialized .slick-slide[data-v-4dc0f449] {
    display: block;
}
.slick-slide[data-v-4dc0f449] {
    display: none;
    float: left;
    height: 100%;
    min-height: 1px;
```

but in production SSR nothing `.slick-initialized` :
```css
.slick-slide[data-v-4dc0f449] {
    display: none;
    float: left;
    height: 100%;
    min-height: 1px;
}
```

why is happened ?
